openapi: 3.2.0
info:
  title: Payments API V2 Payment Accounts - Bank API
  description: '# Introduction

    Payments API v2 enables payers to:

    - Create and manage recipients at an aggregator or payer level

    - Create and manage destination payment accounts at an aggregator or payer level

    - Create and manage payments for Portal acceptance

    - Create payout transactions for immediate disbursement


    # Idempotent Requests

    The API supports **Idempotency** for safely retrying requests without performing the same operation twice for **Create Payment** and **Create Transaction** endpoints.'
  contact: {}
  version: '2'
servers:
- url: http://example.com
  variables: {}
security:
- httpBearer: []
tags:
- name: Payment Accounts - Bank
paths:
  /api/v2/{payer_id}/accounts/{recipient_id}/banks:
    post:
      tags:
      - Payment Accounts - Bank
      summary: Create Bank Account
      operationId: CreateBankAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBankAccountRequest'
            example:
              account_number: '123456789'
              routing_number: 051504597
              account_type: CHECKING
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
      - Payment Accounts - Bank
      summary: Get Bank Accounts
      operationId: GetBankAccounts
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/v2/{payer_id}/accounts/{recipient_id}/banks/{account_id}:
    get:
      tags:
      - Payment Accounts - Bank
      summary: Get Bank Account
      operationId: GetBankAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: account_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - Payment Accounts - Bank
      summary: Delete Bank Account
      operationId: DeleteBankAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: account_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    CreateBankAccountRequest:
      title: CreateBankAccountRequest
      required:
      - account_number
      - routing_number
      - account_type
      type: object
      properties:
        account_number:
          type: string
        routing_number:
          type: string
        account_type:
          type: string
      example:
        account_number: '123456789'
        routing_number: 051504597
        account_type: CHECKING
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
