openapi: 3.2.0
info:
  title: Payments API V2 Authentication API
  description: '# Introduction

    Payments API v2 enables payers to:

    - Create and manage recipients at an aggregator or payer level

    - Create and manage destination payment accounts at an aggregator or payer level

    - Create and manage payments for Portal acceptance

    - Create payout transactions for immediate disbursement


    # Idempotent Requests

    The API supports **Idempotency** for safely retrying requests without performing the same operation twice for **Create Payment** and **Create Transaction** endpoints.'
  contact: {}
  version: '2'
servers:
- url: http://example.com
  variables: {}
security:
- httpBearer: []
tags:
- name: Authentication
  description: OAuth 2.0 is used for authentication and authorization to the API. Client ID and Secret Key can be generated in the Developer Portal.
paths:
  /oauth2/token:
    post:
      tags:
      - Authentication
      summary: Auth Token
      operationId: AuthToken
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            encoding: {}
            schema:
              required:
              - grant_type
              type: object
              properties:
                grant_type:
                  type: string
                  example: client_credentials
        required: false
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
