openapi: 3.2.0
info:
  title: Payments API V2 Payment Accounts - PayPal API
  description: '# Introduction

    Payments API v2 enables payers to:

    - Create and manage recipients at an aggregator or payer level

    - Create and manage destination payment accounts at an aggregator or payer level

    - Create and manage payments for Portal acceptance

    - Create payout transactions for immediate disbursement


    # Idempotent Requests

    The API supports **Idempotency** for safely retrying requests without performing the same operation twice for **Create Payment** and **Create Transaction** endpoints.'
  contact: {}
  version: '2'
servers:
- url: http://example.com
  variables: {}
security:
- httpBearer: []
tags:
- name: Payment Accounts - PayPal
paths:
  /api/v2/{payer_id}/accounts/{recipient_id}/paypal:
    post:
      tags:
      - Payment Accounts - PayPal
      summary: Create PayPal Account
      operationId: CreatePayPalAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePayPalAccountRequest'
            example:
              email: email@domain.com
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    get:
      tags:
      - Payment Accounts - PayPal
      summary: Get PayPal Accounts
      operationId: GetPayPalAccounts
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/v2/{payer_id}/accounts/{recipient_id}/paypal/{account_id}:
    get:
      tags:
      - Payment Accounts - PayPal
      summary: Get PayPal Account
      operationId: GetPayPalAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: account_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /api/v2/{payer_id}/accounts/{recipient_id}/paypal/{account_di}:
    delete:
      tags:
      - Payment Accounts - PayPal
      summary: Delete PayPal Account
      operationId: DeletePayPalAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: account_di
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    CreatePayPalAccountRequest:
      title: CreatePayPalAccountRequest
      required:
      - email
      type: object
      properties:
        email:
          type: string
      example:
        email: email@domain.com
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
