openapi: 3.2.0
info:
  title: Payments API V2 Payment Accounts - Card API
  description: '# Introduction

    Payments API v2 enables payers to:

    - Create and manage recipients at an aggregator or payer level

    - Create and manage destination payment accounts at an aggregator or payer level

    - Create and manage payments for Portal acceptance

    - Create payout transactions for immediate disbursement


    # Idempotent Requests

    The API supports **Idempotency** for safely retrying requests without performing the same operation twice for **Create Payment** and **Create Transaction** endpoints.'
  contact: {}
  version: '2'
servers:
- url: http://example.com
  variables: {}
security:
- httpBearer: []
tags:
- name: Payment Accounts - Card
paths:
  /api/v2/{payer_id}/accounts/{recipient_id}/cards:
    post:
      tags:
      - Payment Accounts - Card
      summary: Create Card Account
      operationId: CreateCardAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCardAccountRequest'
            example:
              card_number: '4515300011000001'
              exp_date: 2030-01
        required: true
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /payer-api/v2/{payer_id}/accounts/{recipient_id}/cards/{account_id}:
    get:
      tags:
      - Payment Accounts - Card
      summary: Get Card Account
      operationId: GetCardAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: account_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
    delete:
      tags:
      - Payment Accounts - Card
      summary: Delete Card Account
      operationId: DeleteCardAccount
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: account_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
  /payer-api/v2/{payer_id}/accounts/{recipient_id}/cards:
    get:
      tags:
      - Payment Accounts - Card
      summary: Get Card Accounts
      operationId: GetCardAccounts
      parameters:
      - name: payer_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: recipient_id
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
components:
  schemas:
    CreateCardAccountRequest:
      title: CreateCardAccountRequest
      required:
      - card_number
      - exp_date
      type: object
      properties:
        card_number:
          type: string
        exp_date:
          type: string
      example:
        card_number: '4515300011000001'
        exp_date: 2030-01
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
